project_id = "workline-co"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://worklineco.com"
additional_redirect_urls = [
  "https://worklineco.com",
  "https://worklineco.com/auth/callback",
  "https://worklineco.com/login",
  "https://www.worklineco.com",
  "https://www.worklineco.com/auth/callback",
  "https://www.worklineco.com/login",
  "http://localhost:3001",
  "http://localhost:3001/auth/callback",
  "http://localhost:3001/login"
]
jwt_expiry = 3600
enable_signup = true

[db]
port = 54322
major_version = 15
